# Generated by Django 4.2.15 on 2024-08-10 10:45

import pathlib

import django.core.files.storage
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import utils.files


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImagePrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("date_deleted", models.DateTimeField(blank=True, null=True)),
                (
                    "prompt",
                    models.TextField(
                        help_text="Stores the prompt provided by the user"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        storage=django.core.files.storage.FileSystemStorage(
                            location=pathlib.PureWindowsPath("D:/aimage/src")
                        ),
                        upload_to=utils.files.RenameFile(
                            "files/image_prompt/{instance.prompt}/{instance.id}.{extension}"
                        ),
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=("jpeg", "png", "jpg")
                            )
                        ],
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Image Prompt",
                "verbose_name_plural": "Image Prompts",
            },
        ),
    ]
